<a href="https://colab.research.google.com/github/sanjana-mishra/Python/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#PyTorch 

import numpy as np
import torch



In [15]:
#create pytorch tensor

my_tensor = torch.tensor ([[1,2,3],[4,5,6],[7,8,9]],dtype = torch.float32)
my_tensor.shape
type(my_tensor)
my_tensor.dtype


torch.float32

In [16]:
#interchange numpy with torch

my_array = np.array([[1,2,3], [4,5,6]], dtype = np.float32)
new_tensor = torch.tensor(my_array)
new_tensor.dtype
new_array = new_tensor.numpy()
my_tensor.device


device(type='cpu')

In [17]:
#to check available gpu

torch.cuda.is_available()

True

In [18]:
my_tensor.device

device(type='cpu')

In [19]:
torch.cuda.device_count()

1

In [20]:
torch.cuda.get_device_name()

'Tesla T4'

In [21]:
my_tensor.cuda()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], device='cuda:0')

In [22]:
my_tensor = my_tensor.cuda()

In [ ]:
#good practice to not hard code cuda in program/code

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
my_tensor = 


a = torch.randn

In [35]:
#BAsic operations

a = torch.rand(10,10)
b = torch.eye(3)
print(a)

tensor([[0.8134, 0.0829, 0.6370, 0.6963, 0.8067, 0.9674, 0.1262, 0.9882, 0.9644,
         0.7374],
        [0.4376, 0.6310, 0.1707, 0.3705, 0.3785, 0.7021, 0.0831, 0.8471, 0.8581,
         0.5210],
        [0.5559, 0.1746, 0.0706, 0.7361, 0.3340, 0.4871, 0.3824, 0.2941, 0.4899,
         0.1650],
        [0.8160, 0.6727, 0.5412, 0.6275, 0.3544, 0.5126, 0.4922, 0.8044, 0.6140,
         0.9009],
        [0.8656, 0.1855, 0.2686, 0.0492, 0.1201, 0.8544, 0.5663, 0.0532, 0.1547,
         0.9337],
        [0.2366, 0.3071, 0.4658, 0.4801, 0.5290, 0.1068, 0.9458, 0.9818, 0.3451,
         0.9393],
        [0.7861, 0.9447, 0.6806, 0.5112, 0.3219, 0.8614, 0.1770, 0.8715, 0.9662,
         0.2295],
        [0.6158, 0.6328, 0.5194, 0.3577, 0.7650, 0.8321, 0.6575, 0.0177, 0.1795,
         0.1065],
        [0.9519, 0.9422, 0.4335, 0.3619, 0.4272, 0.2766, 0.2867, 0.4550, 0.1535,
         0.3148],
        [0.5141, 0.7650, 0.9787, 0.3327, 0.7973, 0.7056, 0.6617, 0.9325, 0.0165,
         0.6912]])


In [27]:
#arithmetic ops are same as numpy

c = a@b
print(c)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [29]:
#slicing

d = c[:, 0].shape
print(d)

torch.Size([3])


In [36]:
#reshaping

a.shape

torch.Size([10, 10])

In [37]:
a.reshape(20,5)

tensor([[0.8134, 0.0829, 0.6370, 0.6963, 0.8067],
        [0.9674, 0.1262, 0.9882, 0.9644, 0.7374],
        [0.4376, 0.6310, 0.1707, 0.3705, 0.3785],
        [0.7021, 0.0831, 0.8471, 0.8581, 0.5210],
        [0.5559, 0.1746, 0.0706, 0.7361, 0.3340],
        [0.4871, 0.3824, 0.2941, 0.4899, 0.1650],
        [0.8160, 0.6727, 0.5412, 0.6275, 0.3544],
        [0.5126, 0.4922, 0.8044, 0.6140, 0.9009],
        [0.8656, 0.1855, 0.2686, 0.0492, 0.1201],
        [0.8544, 0.5663, 0.0532, 0.1547, 0.9337],
        [0.2366, 0.3071, 0.4658, 0.4801, 0.5290],
        [0.1068, 0.9458, 0.9818, 0.3451, 0.9393],
        [0.7861, 0.9447, 0.6806, 0.5112, 0.3219],
        [0.8614, 0.1770, 0.8715, 0.9662, 0.2295],
        [0.6158, 0.6328, 0.5194, 0.3577, 0.7650],
        [0.8321, 0.6575, 0.0177, 0.1795, 0.1065],
        [0.9519, 0.9422, 0.4335, 0.3619, 0.4272],
        [0.2766, 0.2867, 0.4550, 0.1535, 0.3148],
        [0.5141, 0.7650, 0.9787, 0.3327, 0.7973],
        [0.7056, 0.6617, 0.9325, 0.0165, 0.6912]])

In [45]:
#concatenation

a = torch.tensor ([[1,2,3],[4,5,6],[7,8,9]],dtype = torch.float32)
b = torch.ones(3,3)

In [39]:
a

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [40]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [41]:
#concatenating a and b

print(torch.concat((a,b), dim=0))#row-wise(dim=0)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [42]:
#concatenating a and b

print(torch.concat((a,b), dim=1))#col-wise(dim=1)

tensor([[1., 2., 3., 1., 1., 1.],
        [4., 5., 6., 1., 1., 1.],
        [7., 8., 9., 1., 1., 1.]])


In [43]:
a.shape


torch.Size([3, 3])

In [44]:
#multi-dimension tensors

a = torch.randn(size=(10,10,10))
a.shape

torch.Size([10, 10, 10])

In [48]:
#concatenation

a = torch.tensor ([[1,2,3],[4,5,6],[7,8,9]],dtype = torch.float32)
b = torch.ones(3,3)

In [50]:
#concatenate a and b along an extra dmension

a = a.unsqueeze(0) #inside the paranthesis is the dimension argument
b = b.unsqueeze(0)
c = torch.concat((a,b), dim = 0)
print(c.shape)


torch.Size([2, 3, 3])


In [51]:
a.shape

torch.Size([1, 3, 3])

In [52]:
a = a.squeeze() ##destorys extra dim
print(a.shape)

torch.Size([3, 3])


In [ ]:
##DEFINE SIMPLE NEURAL NETWORK
#Neural Networks with PyTorch

class MyModel (torch.nn.Module):
  def __init__ (self):
    super(MyModel, self).__init__()
    self.fc1 = torch.nn.Linear(4, 8)
    self.relu1 = torch.nn.ReLU()
    self.fc2 = torch.nn.Linear(8, 1)
    self.relu2 = torch.nn.ReLU()
def forward(self, x):
  x = self.fcl(x)
  x = self.relu1(x)
  x = self.fc2(x)
  out = self.fc2(x)
  return out



In [ ]:
##sequential

seq_model = torch.nn.Sequential(
    torch.nn.Linear(4, 8),
    torch.nn.ReLU(),
    torch.nn.Linear(8, 1)
)

In [54]:
#autograd--automates the differntiation and back propogation steps

a = torch.tensor ([[1,2,3],[4,5,6],[7,8,9]],dtype = torch.float32, requires_grad=True)
print(a.grad)
print(a.grad_fn)

None
None


In [62]:
a = torch.tensor ([[1,2,3],[4,5,6],[7,8,9]],dtype = torch.float32, requires_grad=True)
y = a + 2
z = y * y
out = torch.mean(z)
print(out)

tensor(55.6667, grad_fn=<MeanBackward0>)


In [63]:
out.backward

<bound method Tensor.backward of tensor(55.6667, grad_fn=<MeanBackward0>)>

In [64]:
a.grad

In [69]:
a.detach().cpu().numpy()

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [70]:
a.device

device(type='cpu')